[project]
name = "django-ibmi"
description = "Db2 for i adapter for Django"
license = "Apache-2.0"
keywords = ["django", "web framework", "ibm", "ibmi", "db2"]
version = "0.1.0-dev"
dynamic = ["classifiers"]
readme = "README.md"
authors = [
    {name = "Korinne Adler", email = "kadler@us.ibm.com"},
    {name = "Naveen Ram ", email = "naveen.ram@ibm.com"}
]
requires-python = '>=3.10'
dependencies = [
    'Django (>=5.2)',
    'pyodbc (>=5.0)',
    'pytz'
]

[dependency-groups]
test = [
    "pytest >=7.2.1; python_version>='3.11'",
    "pytest >=6.2.5; python_version~='3.10'",
]
lint = [
    "flake8",
]
dev = [
    { include-group = "test" },
    { include-group = "lint" },
]

[project.entry-points."django.db.backends"]
django_ibmi = "django_ibmi"

[tool.poetry]
classifiers =[
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Framework :: Django :: 5.2",
]
packages = [
    {include = "django_ibmi"}
]
requires-poetry = '>=2.0,<3.0'

[build-system]
requires = ["poetry-core (>=2.0.0,<3.0.0)"]
build-backend = "poetry.core.masonry.api"
